[build]
command = "yarn db:generate && yarn build"

[template.environment]
DATABASE_URL="database"
BASE_URL="The url of the application"
NEXT_PUBLIC_BASE_URL="The url of the application"
NEXTAUTH_URL="The url of the application"
NEXTAUTH_SECRET="secret"